# -*- coding: utf-8 -*-
"""Day 3 Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qo4XURW0xW8mauP7ASrnIjXv_diC6HFV
"""

from matplotlib import pyplot as plt

"""# (Part 1): Creating and Customizing Our First Plots"""

print(plt.style.available)

plt.style.use('bmh')
#plt.xkcd()
ages_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

dev_y = [38496, 42000, 46752, 49320, 53200, 
         56000, 62316, 64928, 67317, 68748, 73752]
# plt.plot(ages_x, dev_y, 'k--', label='All Devs')
plt.plot(ages_x, dev_y, color='#444444', linestyle='--', marker=".", label='All Devs')

# py_dev_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
py_dev_y = [45372, 48876, 53850, 57287, 63016,
            65998, 70003, 70000, 71496, 75370, 83640]
plt.plot(ages_x, py_dev_y, color='c', marker="o",label='Python')

js_dev_y = [37810, 43515, 46823, 49293, 53437, 
            56373, 62375, 66674, 68745, 68746, 74583]
plt.plot(ages_x, js_dev_y, color='m', linewidth=3,label='JavaScript')

plt.xlabel('Ages')
plt.ylabel('Median Salary')
plt.title('Median Salary (USD) by Age')

#plt.legend(['All Devs', 'Python'])
plt.legend()

plt.grid(True)
plt.tight_layout()

#plt.savefig('plot.png')
# plt.show()

"""# (Part 2): Bar Charts and Analyzing Data from CSVs"""

from matplotlib import pyplot as plt
import numpy as np

plt.style.use('fivethirtyeight')
ages_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

x_indexes = np.arange(len(ages_x))
width=0.25

dev_y = [38496, 42000, 46752, 49320, 53200, 
         56000, 62316, 64928, 67317, 68748, 73752]
plt.bar(x_indexes - width, dev_y, width=width, color='#444444', label='All Devs')

py_dev_y = [45372, 48876, 53850, 57287, 63016,
            65998, 70003, 70000, 71496, 75370, 83640]
plt.bar(x_indexes, py_dev_y, width=width, color='c',label='Python')

js_dev_y = [37810, 43515, 46823, 49293, 53437, 
            56373, 62375, 66674, 68745, 68746, 74583]
plt.bar(x_indexes + width, js_dev_y, width=width, color='m',label='JavaScript')

plt.xlabel('Ages')
plt.ylabel('Median Salary')
plt.title('Median Salary (USD) by Age')

plt.tight_layout()

plt.legend()

#plt.xticks(ticks=x_indexes, labels=ages_x)

pip install pandas

import csv
import numpy as np
import pandas as pd
from collections import Counter
from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

with open('data.csv') as csv_file:
  csv_reader = csv.DictReader(csv.file)

# data = pd.read_csv('data.csv')

language_counter = Counter()

for row in csv_reader: 
    language_counter.update(row['LanguagesWorkedWith'].split(';'))

languages= []
popularity= []

for item in language.counter.most_common(15):
  languages.append(item[0])
  popularity.append(item[0])

plt.barh(languages, popularity)   #to make it horrizontal/easier to read 

plt.ylabel('Programing Languages')   #switch labels for barh
plt.xlabel('Programing Languages')
plt.title('Most Popular Languages')

plt.tight_layout()

#print(language_counter)
#print(language_counter.most_common(15))

"""# (Part 3): Pie Charts"""

from matplotlib import pyplot as plt
plt.style.use("fivethirtyeight")

slices= [60, 40, 30, 20]
labels = ['Sixty','Forty', 'Extra1', 'Extra2']
colors=['blue', 'red', 'yellow', 'green']

plt.pie(slices, labels=labels, wedgeprops={'edgecolor': 'black'})

plt.title("My Awesome Pie Chart")
plt.tight_layout()

plt.show()

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

# Language Popularity
slices = [59219, 55466, 47544, 36443, 35917]
labels = ['JavaScript', 'HTML/CSS', 'SQL', 'Python', 'Java']

explode = [0, 0, 0, 0.1, 0]

plt.pie(slices, labels=labels, explode=explode, shadow= True,startangle= 90,
        autopct='%1.1f%%', wedgeprops={'edgecolor': 'black'})
# startangle= 90 makes it rotate

plt.title("My Awesome Pie Chart")
plt.tight_layout()

plt.show()

"""# (Part 4): Stack Plots"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")


minutes = [1, 2, 3, 4, 5, 6, 7, 8, 9]

player1 = [1, 2, 3, 3, 4, 4, 4, 4, 5]
player2 = [1, 1, 1, 1, 2, 2, 2, 3, 4]
player3 = [1, 1, 1, 2, 2, 2, 3, 3, 3]

labels = ['player1', 'player2', 'player3']
colors = ['#6d904f', '#fc4f30', '#008fd5'] 

# plt.pie([1, 1, 1], labels=["Player 1", "Player2", "Player3"])
plt.stackplot(minutes, player1, player2, player3, labels=labels, colors=colors)

plt.legend(loc=('upper left'))

plt.title("My Awesome Stack Plot")
plt.tight_layout()
plt.show()

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")


minutes = [1, 2, 3, 4, 5, 6, 7, 8, 9]

player1 = [8, 6, 5, 5, 4, 2, 1, 1, 0]
player2 = [0, 1, 2, 2, 2, 4, 4, 4, 4]
player3 = [0, 1, 1, 1, 2, 2, 3, 3, 4]

labels = ['player1', 'player2', 'player3']
colors = ['#008fd5', 'm', '#fc4f30']

plt.stackplot(minutes, player1, player2, player3, labels=labels, colors=colors)

plt.legend(loc=(0.07, 0.05))

plt.title("My Awesome Stack Plot")
plt.tight_layout()
plt.show()

# Colors:
# Blue = #008fd5
# Red = #fc4f30
# Yellow = #e5ae37
# Green = #6d904f

"""# (Part 5): Filling Area on Line Plots"""

import pandas as pd 
from matplotlib import pyplot as plt

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/05-Fill_Betweens/data.csv'
df1 = pd.read_csv(url)

print(df1)

import pandas as pd 
from matplotlib import pyplot as plt

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/05-Fill_Betweens/data.csv'
data = pd.read_csv(url)

ages = data['Age']
dev_salaries = data['All_Devs']
py_salaries = data['Python']
js_salaries = data['JavaScript']

plt.plot(ages, dev_salaries, color='#444444',
         linestyle='--', label='All Devs')

plt.plot(ages, py_salaries, label='Python')

# overall_median = 57287

plt.fill_between(ages, py_salaries, dev_salaries,
                 where=(py_salaries > dev_salaries),
                 interpolate=True, alpha=0.25, label='Above Avg')

plt.fill_between(ages, py_salaries, dev_salaries,
                 where=(py_salaries <= dev_salaries),
                 interpolate=True, color='red', alpha=0.25, label='Below Avg')

plt.legend()

plt.title('Median Salary (USD) by Age')
plt.xlabel('Ages')
plt.ylabel('Median Salary (USD)')

plt.tight_layout()

plt.show()

"""# (Part 6): Histograms"""

import pandas as pd 
from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

ages = [18, 19, 21, 25, 26, 26, 30, 32, 38, 45, 55]
bins = [10, 20, 30, 40, 50, 60]

plt.hist(ages, bins=bins, edgecolor='black')

plt.title('Ages of Respondents')
plt.xlabel('Ages')
plt.ylabel('Total Respondents')

plt.tight_layout()

plt.show()

import pandas as pd 
from matplotlib import pyplot as plt

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/06-Histograms/data.csv'
data = pd.read_csv(url)

plt.style.use('fivethirtyeight')

ids = data['Responder_id']
ages = data['Age']

bins = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

plt.hist(ages, bins=bins, edgecolor='black', log=True)
#log = True puts it on a logrithmic scale for y
median_age = 29
color = '#fc4f30'

plt.axvline(median_age, color=color, label='Age Median', linewidth=2)
# axvline means axis verticle line
plt.legend()

plt.title('Ages of Respondents')
plt.xlabel('Ages')
plt.ylabel('Total Respondents')

plt.tight_layout()

plt.show()

"""# (Part 7): Scatter Plots"""

import pandas as pd
from matplotlib import pyplot as plt

plt.style.use('seaborn')

x = [5, 7, 8, 5, 6, 7, 9, 2, 3, 4, 4, 4, 2, 6, 3, 6, 8, 6, 4, 1]
y = [7, 4, 3, 9, 1, 3, 2, 5, 2, 4, 8, 7, 1, 6, 4, 9, 7, 7, 5, 1]

colors = [7, 5, 9, 7, 5, 7, 2, 5, 3, 7, 1, 2, 8, 1, 9, 2, 5, 6, 7, 5]
sizes = [209, 486, 381, 255, 191, 315, 185, 228, 174,
         538, 239, 394, 399, 153, 273, 293, 436, 501, 397, 539]

plt.scatter(x,y, s=sizes, c=colors, cmap='Greens', edgecolor='black', linewidth=1, alpha=.75)
#plt.scatter(x,y, s=100, c='green', edgecolor='black', linewidth=1, alpha=.75)
#s is size, c is color, to change the shape of dots its marker='', alpha controls transparency

cbar=plt.colorbar()
cbar.set_label('Satisfaction')

plt.tight_layout()

plt.show()

import pandas as pd
from matplotlib import pyplot as plt

plt.style.use('seaborn')

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/07-ScatterPlots/2019-05-31-data.csv'
data = pd.read_csv(url)

view_count = data['view_count']
likes = data['likes']
ratio = data['ratio']

plt.scatter(view_count, likes, c=ratio, cmap='summer',
            edgecolor='black', linewidth=1, alpha=0.75)

cbar = plt.colorbar()
cbar.set_label('Like/Dislike Ratio')

plt.xscale('log')
plt.yscale('log')

plt.title('Trending YouTube Videos')
plt.xlabel('View Count')
plt.ylabel('Total Likes')

plt.tight_layout()

plt.show()

"""# (Part 8): Plotting Time Series Data"""

import pandas as pd
from datetime import datetime, timedelta
from matplotlib import pyplot as plt
from matplotlib import dates as mpl_dates

plt.style.use('seaborn')

dates = [
    datetime(2019, 5, 24),
    datetime(2019, 5, 25),
    datetime(2019, 5, 26),
    datetime(2019, 5, 27),
    datetime(2019, 5, 28),
    datetime(2019, 5, 29),
    datetime(2019, 5, 30)
]

y = [0, 1, 3, 4, 6, 5, 7]

plt.plot_date(dates,y, linestyle='solid', )

plt.gcf().autofmt_xdate()
date_format = mpl_dates.DateFormatter('%b %d, %Y')

plt.gca().xaxis.set_major_formatter(date_format)

plt.tight_layout()

plt.show()

import pandas as pd
from datetime import datetime, timedelta
from matplotlib import pyplot as plt
from matplotlib import dates as mpl_dates

plt.style.use('seaborn')

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/08-TimeSeries/data.csv'
data = pd.read_csv(url)

data['Date'] = pd.to_datetime(data['Date'])   #to turn it into an actual date and not just strings
data.sort_values('Date', inplace=True)

price_date = data['Date']
price_close = data['Close']

plt.plot_date(price_date, price_close, linestyle='solid')

plt.gcf().autofmt_xdate()

plt.title('Bitcoin Prices')
plt.xlabel('Date')
plt.ylabel('Closing Price')

plt.tight_layout()

plt.show()

"""# (Part 9): Plotting Live Data in Real-Time"""

from IPython.display import HTML
import random
from itertools import count
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

plt.style.use('fivethirtyeight')

x_vals = []
y_vals = []

index = count()

def animate(i):
    x_vals.append(next(index))
    y_vals.append(random.randint(0, 5))
    
    plt.cla()
    plt.plot(x_vals, y_vals)

ani = FuncAnimation(plt.gcf(), animate, interval=1000)

#ani = FuncAnimation(plt.gcf(), animate, frames=1000)


HTML(ani.to_html5_video())
#plt.tight_layout()
#plt.show()

from IPython.display import HTML
import random
from itertools import count
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

plt.style.use('fivethirtyeight')

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/09-LiveData/data_gen.py'

x_vals = []
y_vals = []

index = count()


def animate(i):
    data = pd.read_csv(url)
    x = data['x_value']
    y1 = data['total_1']
    y2 = data['total_2']

    plt.cla()

    plt.plot(x, y1, label='Channel 1')
    plt.plot(x, y2, label='Channel 2')

    plt.legend(loc='upper left')
    plt.tight_layout()


ani = FuncAnimation(plt.gcf(), animate, interval=1000)

#ani = FuncAnimation(plt.gcf(), animate, frames=1000)


HTML(ani.to_html5_video())
#plt.tight_layout()
#plt.show()

"""#(Part 10): Subplots"""

import pandas as pd
from matplotlib import pyplot as plt

plt.style.use('seaborn')

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/10-Subplots/data.csv'
data = pd.read_csv(url)
ages = data['Age']
dev_salaries = data['All_Devs']
py_salaries = data['Python']
js_salaries = data['JavaScript']

plt.plot(ages, py_salaries, label='Python')
plt.plot(ages, js_salaries, label='JavaScript')

plt.plot(ages, dev_salaries, color='#444444',
         linestyle='--', label='All Devs')

plt.legend()

plt.title('Median Salary (USD) by Age')
plt.xlabel('Ages')
plt.ylabel('Median Salary (USD)')

plt.tight_layout()

plt.show()

import pandas as pd
from matplotlib import pyplot as plt

plt.style.use('seaborn')

url = 'https://github.com/CoreyMSchafer/code_snippets/raw/master/Python/Matplotlib/10-Subplots/data.csv'
data = pd.read_csv(url)
ages = data['Age']
dev_salaries = data['All_Devs']
py_salaries = data['Python']
js_salaries = data['JavaScript']

fig1, ax1 = plt.subplots()
fig2, ax2 = plt.subplots()
#fig1, (ax1,ax2)=plt.subplots(nrows=2, ncols=2, sharex=True)

ax1.plot(ages, dev_salaries, color='#444444',
         linestyle='--', label='All Devs')

ax2.plot(ages, py_salaries, label='Python')
ax2.plot(ages, js_salaries, label='JavaScript')

ax1.legend()
ax1.set_title('Median Salary (USD) by Age')
ax1.set_ylabel('Median Salary (USD)')

ax2.legend()
ax2.set_xlabel('Ages')
ax2.set_ylabel('Median Salary (USD)')

plt.tight_layout()

plt.show()

#fig1.savefig('fig1.png')
#fig2.savefig('fig2.png')

