# -*- coding: utf-8 -*-
"""Day 5 Mat&Pand Exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jypKrRB1XfYZhGKYrEEvN2Xf8HLh7Bo8

#Matplotlib Exercises

## 1-3
"""

from matplotlib import pyplot as plt
import pandas as pd 

df = pd.read_csv('/content/company_sales_data.csv')
df

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd 
from matplotlib import pyplot as plt

df = pd.read_csv('/content/company_sales_data.csv')

month_x= df['month_number']
profit_y= df['total_profit']
unit_y = df['total_units']

plt.plot(month_x,profit_y, linestyle='dotted', color='red', marker= 'o', linewidth=3, label='total profit')
plt.plot(month_x,unit_y, marker= 'o', linewidth=3, label='total units')


plt.xlabel('Month Number')
plt.ylabel('Profit & Units')
plt.title('Units Sold and Profits for Each Month')

plt.legend(loc= 'lower right')

"""## 4"""

import pandas as pd 
from matplotlib import pyplot as plt

df = pd.read_csv('/content/company_sales_data.csv')

x= df['month_number']
y= df['toothpaste']

plt.scatter(x,y)
plt.grid(True)

plt.xlabel('Month Number')
plt.ylabel('Number of Toothpaste Sold')
plt.title('Number of Toothpaste Sold for Each Month')

"""##5"""

from matplotlib import pyplot as plt
import numpy as np

x= df['month_number']

x_indexes = np.arange(len(x))
width=0.3

y_facecream = df['facecream']
plt.bar(x_indexes - width, y_facecream, width=width, color='c', label='Facecream')

y_facewash = df['facewash']
plt.bar(x_indexes, y_facewash, width=width, color='b', label='Facewash')


plt.xlabel('Month Number')
plt.ylabel('Units Sold')
plt.title('Facecream and Facewash Sold for Each Month')

plt.legend()

"""##6"""

from matplotlib import pyplot as plt

x= df['month_number']
y= df['bathingsoap']

plt.bar(x,y)

plt.xlabel('Month Number')
plt.ylabel('Bathing Soaps Sold')
plt.title('Total Profit for Each Month')

plt.savefig('plot.png')

"""## 7"""

y= df['total_profit']
plt.hist(y, edgecolor='black')

plt.title('Profits')

"""##8"""

from matplotlib import pyplot as plt

print(df['facecream'].sum)
slices = [34480, 18515, 69910, 114010, 25410, 18515]
labels = ['facecream','facewash',	'toothpaste',	'bathingsoap',	'shampoo',	'moisturizer']

plt.pie(slices, labels=labels, shadow= True, autopct='%1.1f%%',wedgeprops={'edgecolor': 'black'})

plt.title("Total Sales")

"""##9"""

import pandas as pd
from matplotlib import pyplot as plt

month_x= df['month_number']
bath_y = df['bathingsoap']
face_y = df['facewash']

fig1, ax1 = plt.subplots()
fig2, ax2 = plt.subplots()

ax1.plot(month_x, bath_y, color='#444444',
         linestyle='--', label='Bathing Soap')

ax2.plot(month_x, face_y, label='Face Wash')

ax1.legend()
ax1.set_title('Bathing Soap and Facewash Sold Each Month')
ax1.set_ylabel('Bathing Soap Sold')

ax2.legend()
ax2.set_xlabel('Month Number')
ax2.set_ylabel('Facewash Sold')

"""##10"""

from matplotlib import pyplot as plt  

month_x= df['month_number']

facecream= df['facecream']
facewash = df['facewash']
toothpaste = df['toothpaste']
bathingsoap = df['bathingsoap']
shampoo = df['shampoo']
moisturizer = df['moisturizer']

labels = ['facecream','facewash',	'toothpaste',	'bathingsoap',	'shampoo',	'moisturizer']

plt.stackplot(month_x,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer, labels=labels)

plt.legend(loc=('upper left'))

plt.title("Sales Each Month")

"""#Panda Exercises

##1
"""

import pandas as pd 

df = pd.read_csv('/content/Automobile_data.csv')
#df.head(50)
df

"""##2"""

import pandas as pd 

df = pd.read_csv("Automobile_data.csv", na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]})
#df.fillna('NaN')   #not sure if it worked
#df
df.to_csv("Automobile_data_wo_NAN.csv")

"""##3"""

df.sort_values(by='price', ascending=False, inplace=True)

df.loc[[35], ['company', 'price']]

"""##4"""

company_grp = df.groupby(['company'])

company_grp.get_group('toyota')

"""##5"""

Company = df['company'].value_counts() #of ppl in each country
Company

"""##6"""

company_grp['price'].max()

"""##7"""

company_grp['average-mileage'].mean()

"""##8"""

#df.sort_values(by='price', ascending=True)
df.sort_values(by='price', ascending=False)

"""##9"""

company = df['company'].value_counts() 
company

cylinders = company_grp['num-of-cylinders'].apply(lambda x: x.str.contains('six').sum()) 
cylinders

num = pd.concat([company, cylinders], axis='columns', sort=False) 
num

num.rename(columns={'company': 'Total_Num_Cars', 'num-of-cylinders': 'has_six_cylinders'}, inplace=True)  
num

"""##10"""

df = pd.read_csv('/content/Automobile_data.csv')
df2 = pd.read_csv('/content/company_sales_data.csv')

df = df.append(df2, ignore_index=True, sort=False)

df

